[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dungeon-stats-display"
version = "0.2.0"
description = "Minecraft Hypixel Skyblock Dungeon Stats Display"
requires-python = ">=3.11"
dependencies = [
    "requests",
    "nbt",
    "stickytape",
]

[tool.setuptools.package-dir]
"" = "system/lib"